version: '3.8'

services:
  mongo:
    image: mongo:5 
    container_name: mongo-db
    ports:
      - '27017:27017' 
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - '8081:8081'
    environment:
    - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
    - ME_CONFIG_MONGODB_ADMINPASSWORD=root
    - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017/myDatabase
    - ME_CONFIG_BASICAUTH_USERNAME=admin
    - ME_CONFIG_BASICAUTH_PASSWORD=root
    depends_on:
      - mongo

volumes:
  mongo-data:
