## ---- DATABASE ----
DB_DATABASE_URL: DATABASE_CONNECTION_STRING
DB_LOGGING: false
## ---- GITHUB KEY ----
GITHUB_KEY: GITHUB_KEY

## ---- LOGS ----
# 'verbose' | 'info' | 'warn' | 'error'
LOG_LEVEL: "verbose"
LOG_API_ERROR: false

## ---- SERVER ----
SERVER_PORT: 5004
